Algoritmo "Entrada e Saída de Dados"

// Descrição   : Entrada e Saída de Dados
// Autor(a)    : Rafaela Sousa Coqueiro Garrido
// Data atual  : 05/05/2023
Var
// Seção de Declarações das variáveis 
// primeiro nome
// segundo nome
// idade
// cidade
// endereço

    primeiroNome, segundoNome, cidade, endereco: caractere
    idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo